apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  plugin-devtron-clusterr
  region: us-east-2
  version: "1.25"

nodeGroups:
  - name: devtron-testt
    privateNetworking: true
## Updated containerRuntime from earlier default docker to now default containerd
    containerRuntime: containerd
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    instancesDistribution:
      maxPrice: 0.5
      instanceTypes: ["t3.micro"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
    volumeSize: 20
    labels: {purpose: devtron}
    asgSuspendProcesses: ["AZRebalance"]
